### ISSUE TITLE
Is there any demo app? How to use with Seneca?

### ISSUE THREAD

**Issue by kristianmandrup** [richardzyx/node-microservice#1]
How would I use this with seneca? Please provide an example :) 
Thanks.

**Comment by richardzyx** [comment]
Hi @kristianmandrup , I built this to replace seneca and allow microservices to directly talk to Rabbitmq. It was before Seneca rebuilt their documentations and went through a pivot, but I can cook up a quick example over the weekend if that helps! You can also see a pair of client and server sample under the Example folder.
